members-only/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

members-only/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

members-only/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :user_id, presence: true
end

members-only/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  
  has_many :posts
  
  before_create :create_user_token
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false } 
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def create_user_token
    self.remember_digest = User.digest(User.new_remember_token)
  end
  
end

members-only/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
end

members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render action:'new'
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:content)
  end
end

members-only/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

members-only/app/helpers/application_helper.rb
module ApplicationHelper
end

members-only/app/helpers/posts_helper.rb
module PostsHelper
end

members-only/app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    remember_token = user.remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_digest, User.digest(remember_token))
    self.current_user = user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    user = @current_user ||= User.find_by(remember_digest: remember_token)
    return nil unless user
    user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def sign_out
    current_user.update_attribute(:remember_digest,
                                User.digest(current_user.create_user_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path
    end
  end
end

members-only/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <% if logged_in? %>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log in", login_path %>
          </li>
        <% end %>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

members-only/app/views/posts/index.html.erb
<% if logged_in? %>
  <%= link_to 'Create a new post', new_post_path %>
<% end %>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= post.content %>
    </li>
    <% if logged_in? %>
    <li>
      <%= post.user.name %>
    </li>
    <% end %>
  <% end %>
</ul>

members-only/app/views/posts/new.html.erb
<h1>Create a new post</h1>
<%= form_for @post do |f| %>
  <div>
    <p><%= f.label :content %></p>
    <%= f.text_area :content %>
  </div>
  <%= submit_tag %>
<% end %>
  